<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>f71499c1-bc02-44e4-ac19-3a61f1be2d93</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.7" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.14.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CarHighjack.Domain\CarHighjack.Domain.csproj" />
    <ProjectReference Include="..\CarHighjack.Inftastructure\CarHighjack.Inftastructure.csproj" />
    <ProjectReference Include="..\CarHighjack.ServiceDefaults\CarHighjack.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
